import { Box, Heading } from "@chakra-ui/react";
import Head from "next/head";
import { Inter } from "next/font/google";
import FilterBar from "@/components/FilterBar";
import RecipeList from "@/components/RecipeList";
import NoResults from "@/components/NoResults";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const recipes = []; // placeholder, later from Redux

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <Box p={8}>
          <Heading mb={4}>Recipes</Heading>
          <FilterBar />
          {recipes.length === 0 ? (
            <NoResults />
          ) : (
            <RecipeList recipes={recipes} />
          )}
        </Box>
      </main>
    </>
  );
}
